### ISSUE TITLE
  shots ERR! Error: animation: "slide", +18s

### ISSUE THREAD

**Issue by tjerkw** [bevacqua/shots#10]
45961eShbBVXTLP47/pages/www-derp-com-20130718175600.html, sizes=1024x768 +0ms
  shots ERR! Error: animation: "slide", +18s
{ [Error: animation: "slide",] noStack: true }

Not sure what happened, or what todo. The error message is not really usefull.

**Comment by jariz** [comment]
It appears to crash (with a similar message) on any javascript error. Would be nice if a JS error didn't make the entire program crash.

**Comment by davisshaver** [comment]
Agreed. I filed a issue here with `pageres` team asking if they had ideas.

https://github.com/sindresorhus/pageres/issues/244

Thoughts @bevacqua?

**Comment by jariz** [comment]
I just caught the error in the screenshot phase, preventing it from boiling up to the fatal exception handler.
It seems to be working alright in my own tests.
See #16.
