### ISSUE TITLE
If the URL in the wayback machine is a 302 redirect, blank screenshots are generated.

### ISSUE THREAD

**Issue by KeenRivals** [bevacqua/shots#11]
1. Try to archive www.lasallehs.net
2. After [20101009023408](https://web.archive.org/web/20101009023408/http://lasallehs.net/), all generated screenshots are blank, starting with [20101227224339](https://web.archive.org/web/20101125190320/http://lasallehs.net/). My guess is that shots is not following the redirect on the  homepage after that time.

I'm not sure if this is a bug in shots or waybackpack.

**Comment by bevacqua** [comment]
`waybackpack` is kind of silly - it doesn't follow redirects for some weird reason. Please shoot this upstream so they fix it and we have a better `shots` 👍

**Comment by KeenRivals** [comment]
I see you already [opened an issue with waybackpack](https://github.com/jsvine/waybackpack/issues/10). Thanks!
